### PR TITLE
Add basic unit tests and workflow

### PR DESCRIPTION
**Pull request by sopermaf**
Adds basic unit tests that run the README example using the sample data

Minimum coverage added as starting point

### CODE REVIEW

**Comment by sopermaf** [comment]
@jthomas I noticed during this PR that [parse](https://github.com/jthomas/ai-speed-camera/blob/main/ai_speed_camera/parse.py) doesn't seem to be used?

Any objections to removing it?

**Comment by sopermaf** [comment]
@jthomas can you see the github actions working? They work within my own forked repo, maybe something needs to be activated on your end? You can see mine here https://github.com/sopermaf/ai-speed-camera/pull/1

I thought having them for PRs in future might give us a higher degree of confidence and we could add automated checks for linting etc too, then get on with some fun work?

**Comment by jthomas** [comment]
> @jthomas I noticed during this PR that [parse](https://github.com/jthomas/ai-speed-camera/blob/main/ai_speed_camera/parse.py) doesn't seem to be used?
> 
> Any objections to removing it?

Nope - I think is was a temporary file during development I then integrated back into the main files.

**Comment by jthomas** [comment]
> @jthomas can you see the github actions working? They work within my own forked repo, maybe something needs to be activated on your end? You can see mine here [sopermaf#1](https://github.com/sopermaf/ai-speed-camera/pull/1)
> 
> I thought having them for PRs in future might give us a higher degree of confidence and we could add automated checks for linting etc too, then get on with some fun work?

Good idea - thanks for the work so far. Let me merge this and see if it works.

**Comment by jthomas** [comment]
Update: LGMT -> https://github.com/jthomas/ai-speed-camera/actions/runs/2489005363

**Comment by sopermaf** [comment]
> Update: LGMT -> https://github.com/jthomas/ai-speed-camera/actions/runs/2489005363

Wow nice! :smile: Thanks for reviewing that!

> Nope - I think is was a temporary file during development I then integrated back into the main files.

Oh great! I'm gonna open a PR for running the code quality checks automatically too and I'll remove it as part of that :+1:

**Pull request merged**
